name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
      - 'docs/**'
      - '.github/**'
    branch:
      - '/docs/i'
      - '/documentation/i'
    body:
      - '/ci/i'
      - '/docs/i'
      - '/readme/i'
  - label: 'bugfix'
    branch:
      - '/fix/i'
      - '/hotfix/i'
    body:
      - '/fix/i'
      - '/hotfix/i'
      - '/bug/i'
      - '/broken/i'
  - label: 'feature'
    branch:
      - '/feature/i'
      - '/feat/i'
    body:
      - '/feature/i'
      - '/feat/i'
      - '/refactor/i'
      - '/enhancement/i'
      - '/improve/i'
      - '/revamp/i'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
  - title: '🧹 Chores'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  $CHANGES

  ## :writing_hand: Contributors

  Thanks to everyone who contributed to this release!

  $CONTRIBUTORS

  [:books: `Compare Previous Release`](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION)
