use_assemblyai: true

openai:
  models:
  - temperature: 0.1
    max_tokens: 2048
    model: gpt-4
    system_prompt: Generate a summary with key points in bold and a Next Steps section,
      use Markdown, be a concise tech expert but kind to non-technical readers.
  - temperature: 0.3
    max_tokens: 2048
    model: gpt-4
    system_prompt: Generate a summary with key points in bold and a Next Steps section,
      use Markdown, be a concise tech expert but kind to non-technical readers.
  - temperature: 0.5
    max_tokens: 2048
    model: gpt-4
    system_prompt: Generate a summary with key points in bold and a Next Steps section,
      use Markdown, be a concise tech expert but kind to non-technical readers.
anthropic:
  models:
  - temperature: 0.1
    max_tokens: 2048
    model: claude-3-sonnet-20240229
    system_prompt: Generate a summary with key points in bold and a Next Steps section,
      use Markdown, be a concise tech expert but kind to non-technical readers.
  - temperature: 0.3
    max_tokens: 2048
    model: claude-3-sonnet-20240229
    system_prompt: Generate a summary with key points in bold and a Next Steps section,
      use Markdown, be a concise tech expert but kind to non-technical readers.
  - temperature: 0.5
    max_tokens: 2048
    model: claude-3-sonnet-20240229
    system_prompt: Generate a summary with key points in bold and a Next Steps section,
      use Markdown, be a concise tech expert but kind to non-technical readers.
input_folder: input
output_folder: output
