apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: transcribe-me
  title: Transcribe Me
  description: |
    Transcribe Me is a CLI-driven Python application that transcribes audio files using the OpenAI Whisper API and generates summaries of the transcriptions using both OpenAI's GPT-4 and Anthropic's Claude models.
  tags:
    - python
    - docker
    - ai
spec:
  type: service
  lifecycle: production
  owner: johnnyhuy
  dependsOn:
    - resource:openai-api
    - resource:openai-whisper-api
    - resource:claude-api

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: openai-api
  title: OpenAI API
  description: |
    The OpenAI API is a paid API that transcribes audio files to text.
  tags:
    - ai
spec:
  type: service
  lifecycle: production

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: openai-whisper-api
  description: |
    The OpenAI Whisper API is a paid API that transcribes audio files to text.
  tags:
    - ai
spec:
  type: service
  lifecycle: production

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: claude-api
  title: Claude API
  description: |
    The Claude API is a paid API that generates summaries of text.
  tags:
    - ai
spec:
  type: service
  lifecycle: production
