name: Prerelease

on:
  push:
    tags:
      - 'v*.*.*-*'

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.ref_name }}

    steps:
      - run: make publish-package
      - run: make publish-image
      - uses: release-drafter/release-drafter@v5
        with:
          version: ${{ github.ref_name }}
          publish: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}