name: Prerelease

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

    steps:
    - uses: actions/checkout@v4
    - uses: asdf-vm/actions/install@v3
    - run: make bump-prerelease
    