name: Publish Latest Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - LICENSE
      - '.github/**'
  workflow_dispatch:

permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: make publish-image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          CI: true
          DOCKER_DEFAULT_PLATFORM: ${{ matrix.arch }}