name: Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: release-drafter/release-drafter@v5
        id: drafter
        with:
          version: ${{ github.ref_name }}
          publish: true
      - run: make publish
        env:
          VERSION: ${{ steps.drafter.outputs.tag_name }}