name: Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.drafter.outputs.tag_name }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: release-drafter/release-drafter@v5
        id: drafter
        with:
          publish: false

  publish:
    runs-on: ubuntu-latest
    needs: release

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: make publish
        env:
          VERSION: ${{ needs.release.outputs.tag_name }}
      - uses: release-drafter/release-drafter@v5
        with:
          publish: true