name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

    steps:
    - uses: actions/checkout@v4
    - uses: asdf-vm/actions/install@v3
    - run: make publish-package
    - run: make publish-image
    # - name: Publish release
    #   uses: release-drafter/release-drafter@v5
    #   with:
    #     publish: true
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}