name: Release

on:
  push:
    tags:
      - '*'

permissions: write-all

jobs:
  publish-package:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - uses: asdf-vm/actions/install@v3
      - run: make publish-package

  publish-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: make publish-image
        env:
          DOCKER_DEFAULT_PLATFORM: ${{ matrix.arch }}