name: Version

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          publish: true